// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHdvSfVbsE-0N6-co6pzzSt86HPNfFqI',
    appId: '1:589573102527:web:204ae8803c5a3443da5f0a',
    messagingSenderId: '589573102527',
    projectId: 'rashd-a9e0c',
    authDomain: 'rashd-a9e0c.firebaseapp.com',
    storageBucket: 'rashd-a9e0c.appspot.com',
    measurementId: 'G-3RWRVK7NLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvO4mlxgnfCDGKq3kHbU1aiOp8Cv3oa_g',
    appId: '1:589573102527:android:2cb645306146c30ada5f0a',
    messagingSenderId: '589573102527',
    projectId: 'rashd-a9e0c',
    storageBucket: 'rashd-a9e0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPRxNS9gKSrDpbYwjXpKf8IgIt3zTFu8',
    appId: '1:589573102527:ios:36933fbae651096bda5f0a',
    messagingSenderId: '589573102527',
    projectId: 'rashd-a9e0c',
    storageBucket: 'rashd-a9e0c.appspot.com',
    iosClientId: '589573102527-4chjsc21tku00o5f9nor2o0fuj2espit.apps.googleusercontent.com',
    iosBundleId: 'com.example.rashd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPRxNS9gKSrDpbYwjXpKf8IgIt3zTFu8',
    appId: '1:589573102527:ios:36933fbae651096bda5f0a',
    messagingSenderId: '589573102527',
    projectId: 'rashd-a9e0c',
    storageBucket: 'rashd-a9e0c.appspot.com',
    iosClientId: '589573102527-4chjsc21tku00o5f9nor2o0fuj2espit.apps.googleusercontent.com',
    iosBundleId: 'com.example.rashd',
  );
}
